-- Baseline indexes: performance and uniqueness indexes for public schema.
-- Primary key indexes are omitted (created with tables).
-- Uses CREATE INDEX IF NOT EXISTS.

CREATE INDEX IF NOT EXISTS idx_admin_user_id ON public.admin USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_bch_recon_principal_id ON public.bch_recon USING btree (principal_id);
CREATE INDEX IF NOT EXISTS idx_bch_recon_school_id ON public.bch_recon USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_bch_recon_status_id ON public.bch_recon USING btree (status_id);
CREATE INDEX IF NOT EXISTS cash_event_request_idx ON public.cash_event USING btree (request_id);
CREATE INDEX IF NOT EXISTS cash_event_school_date_idx ON public.cash_event USING btree (school_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_cash_event_school_id ON public.cash_event USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_cash_event_teacher_id ON public.cash_event USING btree (teacher_id);
CREATE INDEX IF NOT EXISTS idx_class_level_id ON public.class USING btree (level_id);
CREATE INDEX IF NOT EXISTS idx_cu_branch_address_id ON public.cu_branch USING btree (address_id);
CREATE INDEX IF NOT EXISTS idx_cu_branch_created_by ON public.cu_branch USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_cu_branch_updated_by ON public.cu_branch USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_cu_dep_event_deposited_by_teacher_id ON public.cu_dep_event USING btree (deposited_by_teacher_id);
CREATE INDEX IF NOT EXISTS idx_cu_dep_event_posted_by_teller_id ON public.cu_dep_event USING btree (posted_by_teller_id);
CREATE INDEX IF NOT EXISTS idx_cu_dep_event_receipt_file_id ON public.cu_dep_event USING btree (receipt_file_id);
CREATE INDEX IF NOT EXISTS idx_cu_dep_event_school_id ON public.cu_dep_event USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_cu_dep_event_status ON public.cu_dep_event USING btree (status);
CREATE INDEX IF NOT EXISTS idx_cu_dep_event_batch_batch ON public.cu_dep_event_batch USING btree (batch_id);
CREATE INDEX IF NOT EXISTS idx_cu_dep_event_batch_school_id ON public.cu_dep_event_batch USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_cu_dep_event_item_collection_id ON public.cu_dep_event_item USING btree (collection_id);
CREATE INDEX IF NOT EXISTS idx_cu_payout_posted_by_teller_id ON public.cu_payout USING btree (posted_by_teller_id);
CREATE INDEX IF NOT EXISTS idx_cu_payout_request_id ON public.cu_payout USING btree (request_id);
CREATE INDEX IF NOT EXISTS idx_cu_payout_requested_by_principal_id ON public.cu_payout USING btree (requested_by_principal_id);
CREATE INDEX IF NOT EXISTS idx_cu_payout_requested_by_teacher_id ON public.cu_payout USING btree (requested_by_teacher_id);
CREATE INDEX IF NOT EXISTS idx_cu_payout_school_id ON public.cu_payout USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_cu_payout_req_created_by ON public.cu_payout_req USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_cu_payout_req_request_id ON public.cu_payout_req USING btree (request_id);
CREATE INDEX IF NOT EXISTS idx_cu_payout_req_school_id ON public.cu_payout_req USING btree (school_id);
CREATE UNIQUE INDEX IF NOT EXISTS day_batches_school_id_teacher_id_batch_date_key ON public.day_bch USING btree (school_id, teacher_id, batch_date);
CREATE INDEX IF NOT EXISTS idx_day_batches_school_date ON public.day_bch USING btree (school_id, batch_date);
CREATE INDEX IF NOT EXISTS idx_day_bch_locked_by ON public.day_bch USING btree (locked_by);
CREATE INDEX IF NOT EXISTS idx_day_bch_teacher_id ON public.day_bch USING btree (teacher_id);
CREATE INDEX IF NOT EXISTS idx_dep_batch_created_by ON public.dep_batch USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_dep_batch_submitted_by ON public.dep_batch USING btree (submitted_by);
CREATE UNIQUE INDEX IF NOT EXISTS uq_deposit_batch_school_week ON public.dep_batch USING btree (school_id, week_start, week_end);
CREATE INDEX IF NOT EXISTS idx_dep_item_batch_id ON public.dep_item USING btree (batch_id);
CREATE INDEX IF NOT EXISTS idx_dep_item_collection_id ON public.dep_item USING btree (collection_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_dep_item_batch_collection ON public.dep_item USING btree (batch_id, collection_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_dep_item_collection ON public.dep_item USING btree (collection_id);
CREATE INDEX IF NOT EXISTS idx_file_upload_uploaded_by ON public.file_upload USING btree (uploaded_by);
CREATE UNIQUE INDEX IF NOT EXISTS gender_name_key ON public.gender USING btree (name);
CREATE INDEX IF NOT EXISTS idx_guardian_address_id ON public.guardian USING btree (address_id);
CREATE INDEX IF NOT EXISTS idx_guardian_created_by ON public.guardian USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_guardian_mobile_trgm ON public.guardian USING gin (mobile gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_guardian_updated_by ON public.guardian USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_guardian_user_id ON public.guardian USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS guardian_type_name_key ON public.guardian_type USING btree (name);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON public.notification USING btree (user_id, is_read);
CREATE UNIQUE INDEX IF NOT EXISTS permissions_permission_name_key ON public.permission USING btree (permission_name);
CREATE INDEX IF NOT EXISTS idx_principal_created_by ON public.principal USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_principal_school_id ON public.principal USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_principal_updated_by ON public.principal USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_principal_user_id ON public.principal USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_report_def_created_by ON public.report_def USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_report_def_updated_by ON public.report_def USING btree (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS report_definitions_name_key ON public.report_def USING btree (name);
CREATE INDEX IF NOT EXISTS idx_role_role_name ON public.role USING btree (lower(role_name));
CREATE UNIQUE INDEX IF NOT EXISTS roles_role_name_key ON public.role USING btree (role_name);
CREATE INDEX IF NOT EXISTS idx_role_perm_permission_id ON public.role_perm USING btree (permission_id);
CREATE INDEX IF NOT EXISTS idx_school_address_id ON public.school USING btree (address_id);
CREATE INDEX IF NOT EXISTS idx_school_created_by ON public.school USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_school_level ON public.school USING btree ("Level");
CREATE INDEX IF NOT EXISTS idx_school_updated_by ON public.school USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_school_acc_branch ON public.school_acc USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_school_acc_created_by ON public.school_acc USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_school_acc_school_id ON public.school_acc USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_school_acc_updated_by ON public.school_acc USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_student_created_by ON public.student USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_student_school_id ON public.student USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_student_updated_by ON public.student USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_student_user_id ON public.student USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_student_user ON public.student USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_student_acc_created_by ON public.student_acc USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_student_acc_school ON public.student_acc USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_student_acc_student ON public.student_acc USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_student_acc_updated_by ON public.student_acc USING btree (updated_by);
CREATE UNIQUE INDEX IF NOT EXISTS student_accounts_student_id_school_id_key ON public.student_acc USING btree (student_id, school_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_student_acc_one_active ON public.student_acc USING btree (student_id) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_sc_by_end ON public.student_class USING btree (student_id, class_id, end_date);
CREATE INDEX IF NOT EXISTS idx_sc_null_end ON public.student_class USING btree (student_id, class_id) WHERE (end_date IS NULL);
CREATE INDEX IF NOT EXISTS idx_student_classes_class ON public.student_class USING btree (class_id);
CREATE INDEX IF NOT EXISTS idx_student_classes_student ON public.student_class USING btree (student_id);
CREATE UNIQUE INDEX IF NOT EXISTS student_classes_student_id_class_id_start_date_key ON public.student_class USING btree (student_id, class_id, start_date);
CREATE INDEX IF NOT EXISTS idx_student_guardian_guardian ON public.student_guardian USING btree (guardian_id);
CREATE INDEX IF NOT EXISTS idx_student_guardian_student ON public.student_guardian USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_student_guardian_type_id ON public.student_guardian USING btree (type_id);
CREATE UNIQUE INDEX IF NOT EXISTS student_guardian_student_id_guardian_id_key ON public.student_guardian USING btree (student_id, guardian_id);
CREATE INDEX IF NOT EXISTS idx_teacher_created_by ON public.teacher USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_teacher_school_id ON public.teacher USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_updated_by ON public.teacher USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_teacher_user_id ON public.teacher USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_teacher_coll_pdf_file_id ON public.teacher_coll USING btree (pdf_file_id);
CREATE INDEX IF NOT EXISTS idx_teacher_coll_school_id ON public.teacher_coll USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_teacher_coll_slip ON public.teacher_coll USING btree (slip_code);
CREATE INDEX IF NOT EXISTS idx_teacher_coll_teacher_id ON public.teacher_coll USING btree (teacher_id);
CREATE UNIQUE INDEX IF NOT EXISTS teacher_coll_unique_week ON public.teacher_coll USING btree (school_id, teacher_id, week_start, week_end);
CREATE UNIQUE INDEX IF NOT EXISTS teacher_coll_unique_week_per_teacher ON public.teacher_coll USING btree (teacher_id, school_id, week_start, week_end);
CREATE UNIQUE INDEX IF NOT EXISTS teacher_collections_school_id_teacher_id_week_start_key ON public.teacher_coll USING btree (school_id, teacher_id, week_start);
CREATE UNIQUE INDEX IF NOT EXISTS teacher_collections_slip_code_key ON public.teacher_coll USING btree (slip_code);
CREATE INDEX IF NOT EXISTS idx_teller_branch ON public.teller USING btree (branch_id);
CREATE INDEX IF NOT EXISTS idx_teller_user_id ON public.teller USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_receipt_id ON public.transactions USING btree (receipt_id);
CREATE INDEX IF NOT EXISTS idx_transactions_request_id ON public.transactions USING btree (request_id);
CREATE INDEX IF NOT EXISTS idx_transactions_student_id ON public.transactions USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_transactions_teacher_id ON public.transactions USING btree (teacher_id);
CREATE INDEX IF NOT EXISTS idx_transactions_teller_id ON public.transactions USING btree (teller_id);
CREATE INDEX IF NOT EXISTS idx_tx_account_id ON public.transactions USING btree (account_id);
CREATE INDEX IF NOT EXISTS idx_tx_account_status_type ON public.transactions USING btree (account_id, status_id, type_id);
CREATE INDEX IF NOT EXISTS idx_tx_created_at ON public.transactions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tx_school_scope ON public.transactions USING btree (account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_tx_status ON public.transactions USING btree (status_id);
CREATE INDEX IF NOT EXISTS idx_tx_student_created ON public.transactions USING btree (student_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tx_type_id ON public.transactions USING btree (type_id);
CREATE INDEX IF NOT EXISTS idx_tx_appr_guardian_id ON public.tx_appr USING btree (guardian_id);
CREATE UNIQUE INDEX IF NOT EXISTS transaction_approvals_transaction_id_guardian_id_key ON public.tx_appr USING btree (transaction_id, guardian_id);
CREATE UNIQUE INDEX IF NOT EXISTS transaction_status_name_key ON public.tx_stat USING btree (name);
CREATE UNIQUE INDEX IF NOT EXISTS transaction_types_name_key ON public.tx_type USING btree (name);
CREATE INDEX IF NOT EXISTS idx_user_email_trgm ON public."user" USING gin (email gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_user_gender_id ON public."user" USING btree (gender_id);
CREATE INDEX IF NOT EXISTS idx_user_name_trgm ON public."user" USING gin ((((first_name || ' '::text) || COALESCE(last_name, ''::text))) gin_trgm_ops);
CREATE UNIQUE INDEX IF NOT EXISTS users_auth_uid_key ON public."user" USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON public."user" USING btree (email);
CREATE INDEX IF NOT EXISTS idx_user_role_created_by ON public.user_role USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_user_role_role_id ON public.user_role USING btree (role_id);
CREATE INDEX IF NOT EXISTS idx_user_role_user_id ON public.user_role USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_roles_user_id_role_id_key ON public.user_role USING btree (user_id, role_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_appr_guardian_id ON public.withdrawal_appr USING btree (guardian_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_appr_status_id ON public.withdrawal_appr USING btree (status_id);
CREATE UNIQUE INDEX IF NOT EXISTS withdrawal_approvals_request_id_guardian_id_key ON public.withdrawal_appr USING btree (request_id, guardian_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_pol_school_id ON public.withdrawal_pol USING btree (school_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_req_guardian_id ON public.withdrawal_req USING btree (guardian_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_req_student_id ON public.withdrawal_req USING btree (student_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_req_teacher_id ON public.withdrawal_req USING btree (teacher_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_status ON public.withdrawal_req USING btree (status_id);
CREATE INDEX IF NOT EXISTS idx_wr_requested_at ON public.withdrawal_req USING btree (requested_at DESC);
CREATE INDEX IF NOT EXISTS idx_wr_student_status ON public.withdrawal_req USING btree (student_id, status_id);
CREATE INDEX IF NOT EXISTS idx_wreq_account_status ON public.withdrawal_req USING btree (account_id, status_id);
CREATE INDEX IF NOT EXISTS idx_wreq_posted_by_account ON public.withdrawal_req USING btree (account_id) WHERE (status_id = '14a7ff70-0a79-47f1-9361-6017d174ae3d'::uuid);
